DROP TABLE NAVER_MEMBER_LOG;
DROP TABLE NAVER_MEMBER;

CREATE TABLE NAVER_MEMBER (
    NAVER_NO  NUMBER NOT NULL,
    NAVER_ID  VARCHAR2(80 BYTE),
    NAVER_NAME VARCHAR2(50 BYTE),
    NAVER_EMAIL   VARCHAR2(50 BYTE),
    NAVER_PHONE   VARCHAR2(30 BYTE)  
);
ALTER TABLE NAVER_MEMBER ADD CONSTRAINT NAVER_MEMBER_PK PRIMARY KEY ( NAVER_NO );


CREATE TABLE NAVER_MEMBER_LOG (
    NAVER_NO  NUMBER NOT NULL,
    NAVER_LOG_DATE DATE
);

ALTER TABLE NAVER_MEMBER_LOG ADD CONSTRAINT NAVER_MEMBER_NAVER_FK
    FOREIGN KEY(NAVER_NO) REFERENCES NAVER_MEMBER(NAVER_NO) 
          ON DELETE CASCADE;

DROP SEQUENCE NAVER_NO_SEQ;
CREATE SEQUENCE NAVER_NO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 10000 CYCLE NOCACHE;


