DROP TABLE QNA_REPLY;
DROP TABLE QNA;

CREATE TABLE QNA
(
    QNA_NO NUMBER NOT NULL PRIMARY KEY,
    MEMBER_ID VARCHAR2(32 BYTE) NOT NULL,
    QNA_TITLE VARCHAR2(100 BYTE) NOT NULL, 
    QNA_CONTENT VARCHAR2(1500 BYTE), 
    QNA_HIT NUMBER,
    QNA_CREATED DATE,
    QNA_MODIFIED DATE
);

DROP SEQUENCE QNA_NO_SEQ;
CREATE SEQUENCE QNA_NO_SEQ NOCACHE;

CREATE TABLE QNA_REPLY
(
    QNA_REPLY_NO NUMBER NOT NULL PRIMARY KEY, 
    QNA_NO NUMBER NOT NULL, 
    MEMBER_ID VARCHAR2(32 BYTE) NOT NULL, 
    QNA_REPLY_CONTENT VARCHAR2(1000 BYTE), 
    QNA_REPLY_CREATED DATE, 
    QNA_REPLY_STATE NUMBER, 
    QNA_REPLY_DEPTH NUMBER, 
    QNA_REPLY_GROUP_NO NUMBER, 
    QNA_REPLY_GROUP_ORD NUMBER
);

DROP SEQUENCE QNA_REPLY_NO_SEQ;
CREATE SEQUENCE QNA_REPLY_NO_SEQ NOCACHE;

ALTER TABLE QNA_REPLY 
    ADD CONSTRAINT QNA_REPLY_QNA_FK FOREIGN KEY(QNA_NO)
        REFERENCES QNA(QNA_NO) ON DELETE CASCADE;
        
INSERT INTO QNA(QNA_NO, MEMBER_ID, QNA_TITLE, QNA_CONTENT, QNA_HIT, QNA_CREATED ,QNA_MODIFIED)
    VALUES(QNA_NO_SEQ.NEXTVAL, 'member456', 'qnatest1','qnatest1',0, SYSDATE ,SYSDATE);
INSERT INTO QNA(QNA_NO, MEMBER_ID, QNA_TITLE, QNA_CONTENT, QNA_HIT, QNA_CREATED ,QNA_MODIFIED)
    VALUES(QNA_NO_SEQ.NEXTVAL, 'member456', 'qnatest2','qnatest2',0, SYSDATE ,SYSDATE);
INSERT INTO QNA(QNA_NO, MEMBER_ID, QNA_TITLE, QNA_CONTENT,  QNA_HIT,QNA_CREATED ,QNA_MODIFIED)
    VALUES(QNA_NO_SEQ.NEXTVAL, 'member456', 'qnatest3','qnatest3', 0 , SYSDATE ,SYSDATE);
INSERT INTO QNA(QNA_NO, MEMBER_ID, QNA_TITLE, QNA_CONTENT, QNA_HIT, QNA_CREATED ,QNA_MODIFIED)
    VALUES(QNA_NO_SEQ.NEXTVAL, 'member456', 'qnatest4','qnatest4', 0, SYSDATE ,SYSDATE);
INSERT INTO QNA(QNA_NO, MEMBER_ID, QNA_TITLE, QNA_CONTENT, QNA_HIT, QNA_CREATED ,QNA_MODIFIED)
    VALUES(QNA_NO_SEQ.NEXTVAL, 'member456', 'qnatest5','qnatest5', 0, SYSDATE ,SYSDATE);

    
COMMIT;
    
