USE SCOTT;

DROP TABLE RESERVATION;

CREATE TABLE RESERVATION
(
    RESER_NO VARCHAR(15) NOT NULL PRIMARY KEY,
    MEMBER_NO BIGINT NOT NULL,
    ROOM_NO BIGINT NOT NULL,
    RESER_CHECKIN VARCHAR(10),
    RESER_CHECKOUT VARCHAR(10),
    RESER_PEOPLE INT NOT NULL,
    RESER_FOOD INT,
    RESER_STATUS INT NOT NULL,
    RESER_REQUEST VARCHAR(50)
);

-- 예약내역
-- 예약(FK)&회원
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_MEMBER_FK
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO); 

DROP TABLE PRICE;

CREATE TABLE PRICE
(
    PRICE_NO VARCHAR(15),
    TOTAL_PRICE INT,
    ROOM_PRICE INT,
    FOOD_PRICE INT,
    TIP_PRICE INT
);

DROP TABLE PAYMENTS;

CREATE TABLE PAYMENTS
(
    RESER_NO VARCHAR(15) NOT NULL,
    IMP_UID VARCHAR(100) NOT NULL,
    RESPONSE VARCHAR(10),
    AMOUNT INT
);

ALTER TABLE PRICE ADD CONSTRAINT PRICE_FK FOREIGN KEY(PRICE_NO) REFERENCES RESERVATION(RESER_NO) ON DELETE CASCADE; 

COMMIT;