DROP TABLE RESERVATION;

CREATE TABLE RESERVATION
(
    RESER_NO VARCHAR2(15 BYTE) NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    ROOM_NO NUMBER NOT NULL,
    NON_NO NUMBER NOT NULL,
    RESER_CHECKIN DATE,
    RESER_CHECKOUT DATE,
    RESER_PEOPLE NUMBER NOT NULL,
    RESER_FOOD NUMBER,
    RESER_STATUS NUMBER NOT NULL,
    RESER_REQUEST VARCHAR2(50 BYTE)
);

DROP TABLE PRICE;

CREATE TABLE PRICE
(
    PRICE_NO VARCHAR2(15 BYTE),
    TOTAL_PRICE NUMBER,
    ROOM_PRICE NUMBER,
    FOOD_PRICE NUMBER,
    TIP_PRICE NUMBER
);

DROP TABLE PAYMENTS;

CREATE TABLE PAYMENTS
(
    RESER_NO VARCHAR2(15 BYTE) NOT NULL,
    IMP_UID VARCHAR2(100 BYTE) NOT NULL,
    RESPONSE VARCHAR2(10 BYTE),
    AMOUNT NUMBER
);

DROP SEQUENCE PRICE_NO_SEQ;
CREATE SEQUENCE PRICE_NO_SEQ NOCACHE;

ALTER TABLE RESERVATION ADD CONSTRAINTS RESERVATION_PK PRIMARY KEY(RESER_NO);
ALTER TABLE PRICE ADD CONSTRAINTS PRICE_FK FOREIGN KEY(PRICE_NO) REFERENCES RESERVATION(RESER_NO) ON DELETE CASCADE; 