DROP TABLE RE_IMAGE;
DROP TABLE REVIEW_REPLY;

DROP TABLE REVIEW;
CREATE TABLE REVIEW
(
    REVIEW_NO NUMBER NOT NULL,
    MEMBER_ID VARCHAR2(32 BYTE) NOT NULL,
    RT_TYPE	  VARCHAR2(30 BYTE)		NOT NULL,
    ROOM_NAME	VARCHAR2(30 BYTE)		NOT NULL,
    REVIEW_TITLE VARCHAR2(100 BYTE) NOT NULL,
    REVIEW_CONTENT VARCHAR2(1500 BYTE),
    REVIEW_CREATED DATE,
    REVIEW_MODIFIED DATE,
    REVIEW_REV_NO NUMBER
);

DROP SEQUENCE REVIEW_NO_SEQ;
CREATE SEQUENCE REVIEW_NO_SEQ NOCACHE;

CREATE TABLE REVIEW_REPLY
(
    REPLY_NO NUMBER NOT NULL,
    REVIEW_NO NUMBER NOT NULL,
    REPLY_CONTENT VARCHAR2(1500 BYTE) NOT NULL,
    REPLY_CREATED DATE,
    REPLY_MODIFIED DATE
);

DROP SEQUENCE REVIEW_REPLY_NO_SEQ;
CREATE SEQUENCE REVIEW_REPLY_NO_SEQ NOCACHE;

CREATE TABLE RE_IMAGE
(
    RE_IMAGE_NO NUMBER NOT NULL,
    REVIEW_NO NUMBER NOT NULL,
    RE_IMAGE_PATH VARCHAR2(300 BYTE),
    RE_IMAGE_SAVED VARCHAR2(40 BYTE),
    RE_IMAGE_ORIGIN VARCHAR2(300 BYTE)
);

DROP SEQUENCE RE_IMAGE_NO_SEQ;
CREATE SEQUENCE RE_IMAGE_NO_SEQ NOCACHE;

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_PK PRIMARY KEY(REVIEW_NO);
ALTER TABLE REVIEW_REPLY ADD CONSTRAINT REVIEW_REPLY_PK PRIMARY KEY(REPLY_NO);
ALTER TABLE RE_IMAGE ADD CONSTRAINT RE_IMAGE_PK PRIMARY KEY(RE_IMAGE_NO);


ALTER TABLE REVIEW_REPLY 
    ADD CONSTRAINT REVIEW_REPLY_REVIEW_FK FOREIGN KEY(REVIEW_NO)
        REFERENCES REVIEW(REVIEW_NO) ON DELETE CASCADE;
        
ALTER TABLE RE_IMAGE
    ADD CONSTRAINT RE_IMAGE_REVIEW_FK FOREIGN KEY(REVIEW_NO)
        REFERENCES REVIEW(REVIEW_NO) ON DELETE CASCADE;


DROP SEQUENCE MEMBER_NO_SEQ;
CREATE SEQUENCE MEMBER_NO_SEQ NOCACHE;
DROP SEQUENCE RESER_NO_SEQ;
CREATE SEQUENCE RESER_NO_SEQ NOCACHE;

INSERT INTO REVIEW (REVIEW_NO, MEMBER_ID, RT_TYPE, ROOM_NAME, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_CREATED, REVIEW_MODIFIED, REVIEW_REV_NO)
    VALUES (REVIEW_NO_SEQ.NEXTVAL, 'member123','싱글', 'a룸', '짱 좋아요', '최고의 호텔!!', SYSDATE,SYSDATE, 5);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_ID, RT_TYPE, ROOM_NAME, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_CREATED, REVIEW_MODIFIED, REVIEW_REV_NO)
    VALUES (REVIEW_NO_SEQ.NEXTVAL, 'member123', '싱글', 'a룸', '경치 최고', '조식 엄청 맛있음!!', SYSDATE,SYSDATE, 5);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_ID, RT_TYPE, ROOM_NAME, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_CREATED, REVIEW_MODIFIED, REVIEW_REV_NO)
    VALUES (REVIEW_NO_SEQ.NEXTVAL, 'member123', '싱글', 'a룸', '최고의 호캉스', '또 오고싶어요~', SYSDATE,SYSDATE, 5);


COMMIT;

INSERT INTO REVIEW_REPLY (REPLY_NO, REVIEW_NO, REPLY_CONTENT, REPLY_CREATED,REPLY_MODIFIED)
    VALUES (REVIEW_REPLY_NO_SEQ.NEXTVAL, 1, '감사합니다!', SYSDATE,SYSDATE);
COMMIT;            
            