DROP TABLE "ROOM";
CREATE TABLE "ROOM" (
	"ROOM_NO"	NUMBER		NOT NULL,
	"RT_NO"	NUMBER		NOT NULL,
	"ROOM_NAME"	VARCHAR2(30 BYTE)		NOT NULL,
	"ROOM_STATUS"	NUMBER		NOT NULL,
	"ROOM_CHECKIN"	DATE		NULL,
	"ROOM_CHECKOUT"	DATE		NULL,
	"ROOM_PRICE"	NUMBER		NOT NULL
);

DROP TABLE "ROOM_TYPE";
CREATE TABLE "ROOM_TYPE" (
	"RT_NO"	NUMBER		NOT NULL,
	"RT_TYPE"	VARCHAR2(30 BYTE)		NOT NULL,
	"RT_MAX"	NUMBER		NOT NULL
);

DROP TABLE "IMAGE";
CREATE TABLE "IMAGE" (
	"IMAGE_NO"	NUMBER		NOT NULL,
	"ROOM_NO"	NUMBER		NOT NULL,
	"IMAGE_PATH"	VARCHAR2(300 BYTE)		NULL,
	"IMAGE_SAVED"	VARCHAR2(40 BYTE)		NULL,
	"IMAGE_ORIGIN"	VARCHAR2(300 BYTE)		NULL
);

DROP SEQUENCE ROOM_SEQ;
DROP SEQUENCE ROOM_TYPE_SEQ;
DROP SEQUENCE IMAGE_SEQ;

CREATE SEQUENCE ROOM_SEQ NOCACHE;
CREATE SEQUENCE ROOM_TYPE_SEQ NOCACHE;
CREATE SEQUENCE IMAGE_SEQ NOCACHE;

ALTER TABLE ROOM
    ADD CONSTRAINT ROOM_PK
        PRIMARY KEY(ROOM_NO);
ALTER TABLE ROOM_TYPE
    ADD CONSTRAINT ROOM_TYPE_PK
        PRIMARY KEY(RT_NO);
ALTER TABLE IMAGE
    ADD CONSTRAINT IMAGE_PK
        PRIMARY KEY(IMAGE_NO);
     
ALTER TABLE ROOM 
    ADD CONSTRAINT ROOM_ROOM_TYPE_FK 
        FOREIGN KEY(RT_NO) REFERENCES ROOM_TYPE(RT_NO)
            ON DELETE CASCADE;
ALTER TABLE IMAGE
    ADD CONSTRAINT IMAGE_ROOM_FK
        FOREIGN KEY(ROOM_NO) REFERENCES ROOM(ROOM_NO)
	ON DELETE CASCADE;

INSERT INTO ROOM_TYPE (RT_NO, RT_TYPE, RT_MAX) VALUES (1, '싱글', 1);
INSERT INTO ROOM_TYPE (RT_NO, RT_TYPE, RT_MAX) VALUES (2, '더블', 2);
INSERT INTO ROOM_TYPE (RT_NO, RT_TYPE, RT_MAX) VALUES (3, '트윈', 2);
COMMIT;

