USE SCOTT;

DROP TABLE ROOM;
DROP TABLE ROOM_TYPE;
DROP TABLE IMAGE;

CREATE TABLE ROOM_TYPE (
	RT_NO	BIGINT	NOT NULL PRIMARY KEY,
	RT_TYPE	VARCHAR(30)	NOT NULL,
	RT_MAX	BIGINT	NOT NULL
);


CREATE TABLE ROOM (
	ROOM_NO BIGINT	NOT NULL auto_increment PRIMARY KEY,
	RT_NO	BIGINT	NOT NULL,
	ROOM_NAME	VARCHAR(300)	NOT NULL,
	ROOM_STATUS	INT	NOT NULL,
	ROOM_CHECKIN	DATE	NULL,
	ROOM_CHECKOUT	DATE	NULL,
    ROOM_PRICE INT NOT NULL
);



CREATE TABLE IMAGE (
	IMAGE_NO BIGINT	NOT NULL auto_increment PRIMARY KEY,
	ROOM_NO	BIGINT NOT NULL,
	IMAGE_PATH	VARCHAR(300) NOT NULL,
	IMAGE_SAVED	VARCHAR(40) NOT NULL,
	IMAGE_ORIGIN VARCHAR(300) NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_ROOM_TO_RESERVATION FOREIGN KEY (
	ROOM_NO
)
REFERENCES ROOM (
	ROOM_NO
);


ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_TYPE_TO_ROOM FOREIGN KEY (
	RT_NO
)
REFERENCES ROOM_TYPE (
	RT_NO
);

ALTER TABLE IMAGE ADD CONSTRAINT FK_ROOM_TO_IMAGE FOREIGN KEY (
	ROOM_NO
)
REFERENCES ROOM (
	ROOM_NO
);

INSERT INTO ROOM_TYPE(RT_NO, RT_TYPE, RT_MAX)
VALUES (1, 'SINGLE', 1);
INSERT INTO ROOM_TYPE(RT_NO, RT_TYPE, RT_MAX)
VALUES (2, 'DOUBLE', 2);
INSERT INTO ROOM_TYPE(RT_NO, RT_TYPE, RT_MAX)
VALUES (3, 'TWIN', 2);

COMMIT;