DROP TABLE USER_LOG;
DROP TABLE USERS;

CREATE TABLE USERS (
    NO  NUMBER NOT NULL,
    ID  VARCHAR2(80 BYTE),
    NAME VARCHAR2(50 BYTE),
    EMAIL   VARCHAR2(50 BYTE),
    PHONE   VARCHAR2(30 BYTE)  
);
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY ( NO );


CREATE TABLE USER_LOG (
    NO  NUMBER NOT NULL,
    LOG_DATE DATE
);

ALTER TABLE USER_LOG ADD CONSTRAINT USER_LOG_USERS_FK
    FOREIGN KEY(NO) REFERENCES USERS(NO) 
          ON DELETE CASCADE;

DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 10000 CYCLE NOCACHE;

select * from users
desc users
select * from user_log
select * from reservation

