DROP TABLE USER_LOG;
DROP TABLE SNS_INFO;
DROP TABLE USERS;

CREATE TABLE USERS (
    NO  NUMBER NOT NULL,
    ID  VARCHAR2(80 BYTE),
    NAME VARCHAR2(50 BYTE),
    EMAIL   VARCHAR2(50 BYTE),
    GENDER  VARCHAR2(20 BYTE),
    PHONE   VARCHAR2(30 BYTE)  
);
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY ( ID );


CREATE TABLE USER_LOG (
    ID  VARCHAR2(80 BYTE),
    LOG_DATE DATE
);
ALTER TABLE USER_LOG ADD CONSTRAINT USER_LOG_PK PRIMARY KEY ( ID );

ALTER TABLE USER_LOG ADD CONSTRAINT USER_LOG_USERS_FK
    FOREIGN KEY(ID) REFERENCES USERS(ID) 
          ON DELETE CASCADE;

DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 10000 CYCLE NOCACHE;

select * from users
insert into users values (no_seq.NEXTVAL, 'test2','test', 'test@test.com', 'F', '010-1234-1234')

desc users
select * from user_log
select * from reservation


INSERT INTO RESERVATION
			(RESER_NO, MEMBER_NO, ROOM_NO, NON_NO, RESER_CHECKIN, RESER_CHECKOUT, RESER_PEOPLE, RESER_FOOD, RESER_STATUS, RESER_REQUEST)
		VALUES
			('RN_SJ460HY10', 7, 1, 1, '22/07/07', '22/07/09', 3, 1, 1, null)